[versions]
kotlin = "2.1.21"
agp = "8.13.2"
koin = "3.5.6"
retrofit = "2.11.0"
okhttp = "4.12.0"
coroutines = "1.9.0"
lifecycle = "2.8.7"
appcompat = "1.7.0"
core-ktx = "1.15.0"
material = "1.12.0"
constraintlayout = "2.2.1"
recyclerview = "1.3.2"
cardview = "1.0.0"
coil = "3.3.0"
timber = "5.0.1"
iconics = "5.4.0"
iconics-typeface = "2.2.0.8-kotlin"
adapterdelegates = "4.3.2"
photoview = "1.0.2"
material-about = "3.1.2"
busybee = "0.0.4"
junit = "4.13.2"
mockito = "3.12.4"
hamcrest = "2.2"
test-core = "1.6.1"
test-runner = "1.6.2"
test-rules = "1.6.1"
test-ext-junit = "1.2.1"
espresso = "3.6.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
coil = { module = "io.coil-kt.coil3:coil-android", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
iconics-core = { module = "com.mikepenz:iconics-core", version.ref = "iconics" }
iconics-material-typeface = { module = "com.mikepenz:material-design-iconic-typeface", version.ref = "iconics-typeface" }
adapterdelegates = { module = "com.hannesdorfmann:adapterdelegates4", version.ref = "adapterdelegates" }
photoview = { module = "io.getstream:photoview", version.ref = "photoview" }
material-about = { module = "com.github.daniel-stoneuk:material-about-library", version.ref = "material-about" }
busybee = { module = "io.americanexpress.busybee:busybee-android", version.ref = "busybee" }
junit = { module = "junit:junit", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
hamcrest = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
androidx-test-core = { module = "androidx.test:core", version.ref = "test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "test-rules" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "test-ext-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
